---
# these are mandatory for steam auth
steam_user:
steam_pass:
# you'll be prompted to fill in this after
# the first ansible run
steam_code:

# these are optional
seven_port:
data_port:
server_name:
